# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: SpringBoot CI/CD pipelinw

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: demo-cluster-1
  GKE_ZONE: us-central1-c


  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        server-id: docker.io
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
       
    - name: Building and pushing department-service
      run: mvn clean package dockerfile:push --file department-service/pom.xml
      env:
        MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Building and pushing user-service
      run: mvn clean package dockerfile:push --file user-service/pom.xml
      env:
        MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Building and pushing service-registry
      run: mvn clean package dockerfile:push --file service-registry/pom.xml
      env:
        MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Building and pushing cloud-gateway
      run: mvn clean package dockerfile:push --file cloud-gateway/pom.xml
      env:
        MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Building and pushing hystrix-dashboard
      run: mvn clean package dockerfile:push --file hystrix-dashboard/pom.xml
      env:
        MAVEN_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  
  Deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: kubectl - Google Cloud GKE cluster.
      uses: ameydev/gke-kubectl-action@master
      env:
        PROJECT_ID: ${{ env.PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GKE_KEY }}
        CLUSTER_NAME: ${{ GKE_CLUSTER }}
        ZONE_NAME: ${{ env.GKE_ZONE }}
      with:
        args: apply -f kubernets-confi-files/

    
